### PR TITLE
Lock workspace even on data loss option

### PR DESCRIPTION
**Pull request by yuryk53**
Added configuration option to Tools -> Options -> Security so that workspace could be locked (primarily on user switch action on Windows [Win+L]) even if some data might be lost (any windows like 'Edit password' are opened).

### CODE REVIEW

**Comment by dlech** [comment]
Hi.

This repository is just a mirror of the official KeePass 2.x source code. Any changes should be submitted to https://sourceforge.net/p/keepass/patches/.

**Comment by yuryk53** [comment]
Hi, are there any docs on how to use that svn repo and how to build that
project? Which branch to commit to. And it seems to me there're no all that
code available which is on github.

Best regards,
Yurii Bilyk

сб, 1 дек. 2018 г. в 02:37, David Lechner <notifications@github.com>:

**Comment by dlech** [comment]
KeePass doesn't use version control. You can still use git and this repository to generate a patch though. For example, here is the patch for the commit in this pull request: https://github.com/dlech/KeePass2.x/commit/ea5448b1fa1d9ede8125c2759021d5af6c80bdcd.patch. Some people also just submit the entire modified file(s).

**Comment by yuryk53** [comment]
Ok, I've got the point (I'll submit the patches in the 'Changes' thread a
bit later than). I'm just interested, if there's any reason, why KeePass
doesn't use version control? I've been working as a software developer for
years and git seems to be the common solution...
Thanks for your time, though.

вс, 2 дек. 2018 г. в 23:16, David Lechner <notifications@github.com>:

**Comment by dlech** [comment]
https://sourceforge.net/p/keepass/discussion/329220/thread/b0bb5457/

**Pull request closed without merging**
